# Generated by Django 2.2.3 on 2019-08-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('tamanho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('processador', models.CharField(max_length=50)),
                ('quantidade_slots', models.IntegerField()),
                ('quantidade_memoria', models.IntegerField()),
                ('video_integrado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacaVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Memoria_ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computador.MemoriaRam')),
                ('placa_mae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computador.PlacaMae')),
                ('placa_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computador.PlacaVideo')),
                ('processador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computador.Processador')),
            ],
        ),
    ]
