# Generated by Django 2.2.3 on 2019-08-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computador',
            old_name='Memoria_ram',
            new_name='memoria_ram',
        ),
    ]
