# Generated by Django 2.2.3 on 2019-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computador', '0004_auto_20190804_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='memoria_ram',
        ),
        migrations.AddField(
            model_name='computador',
            name='memoria_ram',
            field=models.ManyToManyField(related_name='MemoriaRam_Computador', to='computador.MemoriaRam'),
        ),
    ]
