# Generated by Django 2.2.3 on 2019-08-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computador', '0006_auto_20190804_1810'),
    ]

