# Generated by Django 2.2.3 on 2019-08-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computador', '0007_auto_20190804_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='memoria_ram',
        ),
    ]
